import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import Footer from "@/components/Footer";
import { auth } from "../../auth";
import { useQuery, useMutation, useQueryClient, QueryClient, QueryClientProvider } from "@tanstack/react-query";
import QCProviderComponent from "../../providers/queryClient";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const getSession = await auth(); // Fetch session data on the server side

  return (
    <html lang="en">
      <body className={inter.className}>
        <QCProviderComponent>
          <Header session={getSession} user={getSession?.user as any} />
          {/* <p>{JSON.stringify(getSession)}</p> */}
          {children}
          <Footer />
        </QCProviderComponent>
      </body>
    </html>
  );
}
