import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import Footer from "@/components/Footer";
import QCProviderComponent from "../../providers/queryClient";
import { SessionProvider } from "./SessionProvider";
import { AuthProtection } from "./AuthProtection";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QCProviderComponent>
          <SessionProvider>
            <Header />
            {/* <p>dcdsc</p> */}
            <AuthProtection>{children}</AuthProtection>
            <Footer />
          </SessionProvider>
        </QCProviderComponent>
      </body>
    </html>
  );
}
